name: Write Post Daily Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  turso-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod tidy

      - name: Write Post
        env:
          TURSO_DB_URL: ${{ secrets.TURSO_DB_URL }}
          TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}
        run: go run write-post/main.go

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: write-artifact
          path: artifact.json
