name: Write Daily Post

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  write-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install dependencies
        working-directory: write-post
        run: go mod tidy

      - name: Write Post
        working-directory: write-post
        env:
          TURSO_DB_URL: ${{ secrets.TURSO_DB_URL }}
          TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}
        run: go run main.go

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: write-artifact
          path: write-post/artifact.json
